### ISSUE TITLE
Blog link is broken

### ISSUE THREAD

**Issue by gppk** [Think-Engineer/docker-compose_nginx_ssl_demo#1]
You tell me to read the blog link twice, but link it incorrectly twice.

It should be https://think-engineer.com/blog/software/how-to-obtain-an-ssl-certificate-for-a-containerised-web-application-for-free

not https://think-engineer.com/blog/how-to-obtain-an-ssl-certificate-for-a-containerised-web-application-for-free

**Comment by amitchone** [comment]
Thanks for raising this issue. The links were fixed in commit [7ad12417b3c077c768d024ebf33bfe121668ca70](https://github.com/Think-Engineer/docker-compose_nginx_ssl_demo/commit/7ad12417b3c077c768d024ebf33bfe121668ca70).
